// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tour.Infrastructure.Data;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(PackageContext))]
    [Migration("20200229163403_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tour.Domain.Entities.City", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Tour.Domain.Entities.Hotel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("HotelInfoId");

                    b.Property<long>("PackageId");

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.HasIndex("HotelInfoId");

                    b.HasIndex("PackageId");

                    b.ToTable("Hotel");
                });

            modelBuilder.Entity("Tour.Domain.Entities.HotelInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Location");

                    b.Property<float>("Rate");

                    b.Property<int>("Stars");

                    b.Property<string>("Title");

                    b.Property<long?>("cityId");

                    b.HasKey("Id");

                    b.HasIndex("cityId");

                    b.ToTable("HotelInfos");
                });

            modelBuilder.Entity("Tour.Domain.Entities.Package", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("DestinationCityId");

                    b.Property<DateTime>("EndDate");

                    b.Property<long>("OriginCityId");

                    b.Property<DateTime>("StartDate");

                    b.Property<string>("SupportPhone");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("DestinationCityId");

                    b.HasIndex("OriginCityId");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("Tour.Domain.Entities.Transportation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FromDate");

                    b.Property<long>("PackageId");

                    b.Property<DateTime>("ToDate");

                    b.Property<long>("TransportationInfoId");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.HasIndex("TransportationInfoId");

                    b.ToTable("Transportation");
                });

            modelBuilder.Entity("Tour.Domain.Entities.TransportationInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyName");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("TransportationInfos");
                });

            modelBuilder.Entity("Tour.Domain.Entities.Hotel", b =>
                {
                    b.HasOne("Tour.Domain.Entities.HotelInfo", "HotelInformation")
                        .WithMany()
                        .HasForeignKey("HotelInfoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Tour.Domain.Entities.Package")
                        .WithMany("Hotels")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Tour.Domain.Entities.HotelInfo", b =>
                {
                    b.HasOne("Tour.Domain.Entities.City", "city")
                        .WithMany()
                        .HasForeignKey("cityId");
                });

            modelBuilder.Entity("Tour.Domain.Entities.Package", b =>
                {
                    b.HasOne("Tour.Domain.Entities.City", "DestinationCity")
                        .WithMany()
                        .HasForeignKey("DestinationCityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Tour.Domain.Entities.City", "OriginCity")
                        .WithMany()
                        .HasForeignKey("OriginCityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Tour.Domain.Entities.Transportation", b =>
                {
                    b.HasOne("Tour.Domain.Entities.Package")
                        .WithMany("Transportations")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Tour.Domain.Entities.TransportationInfo", "TransportationInformation")
                        .WithMany()
                        .HasForeignKey("TransportationInfoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
