// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tour.Infrastructure.Data;

namespace Infrastructure.EntityFramework.Migrations
{
    [DbContext(typeof(PackageContext))]
    partial class PackageContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tour.Domain.Entities.City", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Tour.Domain.Entities.Hotel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HotelInfoId");

                    b.Property<long?>("PackageId");

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.ToTable("Hotel");
                });

            modelBuilder.Entity("Tour.Domain.Entities.HotelInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<float>("Rate");

                    b.Property<int>("Stars");

                    b.HasKey("Id");

                    b.ToTable("HotelInfos");
                });

            modelBuilder.Entity("Tour.Domain.Entities.Package", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("DestinationCityId");

                    b.Property<DateTime>("EndDate");

                    b.Property<long?>("OriginCityId");

                    b.Property<DateTime>("StartDate");

                    b.Property<string>("SupportPhone");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("DestinationCityId");

                    b.HasIndex("OriginCityId");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("Tour.Domain.Entities.Transportation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FromDate");

                    b.Property<long?>("PackageId");

                    b.Property<DateTime>("ToDate");

                    b.Property<int>("TransportationInfoId");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.ToTable("Transportation");
                });

            modelBuilder.Entity("Tour.Domain.Entities.TransportationInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyName");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("TransportationInfos");
                });

            modelBuilder.Entity("Tour.Domain.Entities.Hotel", b =>
                {
                    b.HasOne("Tour.Domain.Entities.Package")
                        .WithMany("Hotels")
                        .HasForeignKey("PackageId");
                });

            modelBuilder.Entity("Tour.Domain.Entities.Package", b =>
                {
                    b.HasOne("Tour.Domain.Entities.City", "DestinationCity")
                        .WithMany()
                        .HasForeignKey("DestinationCityId");

                    b.HasOne("Tour.Domain.Entities.City", "OriginCity")
                        .WithMany()
                        .HasForeignKey("OriginCityId");
                });

            modelBuilder.Entity("Tour.Domain.Entities.Transportation", b =>
                {
                    b.HasOne("Tour.Domain.Entities.Package")
                        .WithMany("Transportations")
                        .HasForeignKey("PackageId");
                });
#pragma warning restore 612, 618
        }
    }
}
